### ISSUE TITLE
Adicionar loop infinito para exibir menu continuamente. main.py

### ISSUE THREAD

**Issue by FelipeSantos-cco** [Cayozada/ATEdge#1]
Atualmente, o menu é exibido apenas uma vez e, em seguida, o programa termina. 
Isso pode ser inconveniente para os usuários, pois podem acabar clicando em uma tecla errada e saindo do programa "sem querer". 

Para solucionar isso, proponho adicionar um loop infinito que permita a exibição contínua do menu até que o usuário escolha a opção de sair. A nova linha de código será um simples `while True:` adicionado após o método `run` da classe `Menu`.

P.S: **Não realizei teste sobre**

**Comment by Cayozada** [comment]
> Atualmente, o menu é exibido apenas uma vez e, em seguida, o programa termina. Isso pode ser inconveniente para os usuários, pois podem acabar clicando em uma tecla errada e saindo do programa "sem querer".
> 
> Para solucionar isso, proponho adicionar um loop infinito que permita a exibição contínua do menu até que o usuário escolha a opção de sair. A nova linha de código será um simples `while True:` adicionado após o método `run` da classe `Menu`.
> 
> P.S: **Não realizei teste sobre**

Obrigado pela sugestão felipe, ja foi implementado no hotfix de hoje e realmente, um loop faz muito mais sentido nesse caso.
